In [1]:
# Importer nødvendige biblioteker
import pandas as pd
import os

# Sjekk nåværende arbeidskatalog
print("Nåværende arbeidskatalog:", os.getcwd())

# Prøv å lese inn datasettet
try:
    # Last inn datasettet, endre filbanen hvis nødvendig
    df = pd.read_csv('Grocery_dataset.csv')
    print("Datasettet ble lastet inn riktig.")
except FileNotFoundError:
    print("Filen 'Grocery_dataset.csv' ble ikke funnet. Vennligst sjekk filbanen.")

# Hvis filen ble lastet inn riktig, fortsett med oppgavene
if 'df' in locals():  # Sjekk om df eksisterer
    # Oppgave 5: Fjern kolonnene med indeksverdier 0 og 6 og opprett en ny DataFrame
    columns_to_drop = [0, 6]
    Grc_new_df = df.drop(df.columns[columns_to_drop], axis=1)

    # Skriv ut de første radene for å bekrefte at kolonnene er fjernet
    print("Grc_new_df after dropping columns with index 0 and 6:")
    print(Grc_new_df.head())

 # Oppgave 6: Lag to forskjellige DataFrames basert på Outlet_Type
    SupType_1 = Grc_new_df[Grc_new_df['Outlet_Type'] == 'Supermarket Type1']
    SupType_2 = Grc_new_df[Grc_new_df['Outlet_Type'] == 'Supermarket Type2']

    # Skriv ut de første radene for hver DataFrame for å bekrefte
    print("\nSupType_1 DataFrame:")
    print(SupType_1.head())

    print("\nSupType_2 DataFrame:")
    print(SupType_2.head())
else:
    print("Kjøring av koden ble stoppet fordi datasettet ikke ble funnet.")

Nåværende arbeidskatalog: C:\Users\Alaa\OneDrive\Dokumenter\LO
Datasettet ble lastet inn riktig.
Grc_new_df after dropping columns with index 0 and 6:
   Item_Weight Item_Fat_Content  Item_Visibility              Item_Type  \
0         9.30          Low Fat         0.016047                  Dairy
1         5.92          Regular         0.019278            Soft Drinks
2        17.50          Low Fat         0.016760                   Meat
3        19.20          Regular         0.000000  Fruits and Vegetables
4         8.93          Low Fat         0.000000              Household

   Item_MRP  Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0  249.8092                       1999      Medium               Tier 1
1   48.2692                       2009      Medium               Tier 3
2  141.6180                       1999      Medium               Tier 1
3  182.0950                       1998         NaN               Tier 3
4   53.8614                       1987        High               Tier 3

         Outlet_Type  Item_Outlet_Sales
0  Supermarket Type1          3735.1380
1  Supermarket Type2           443.4228
2  Supermarket Type1          2097.2700
3      Grocery Store           732.3800
4  Supermarket Type1           994.7052

SupType_1 DataFrame:
   Item_Weight Item_Fat_Content  Item_Visibility     Item_Type  Item_MRP  \
0         9.30          Low Fat         0.016047         Dairy  249.8092
2        17.50          Low Fat         0.016760          Meat  141.6180
4         8.93          Low Fat         0.000000     Household   53.8614
6        13.65          Regular         0.012741   Snack Foods   57.6588
8        16.20          Regular         0.016687  Frozen Foods   96.9726

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1
2                       1999      Medium               Tier 1
4                       1987        High               Tier 3
6                       1987        High               Tier 3
8                       2002         NaN               Tier 2

         Outlet_Type  Item_Outlet_Sales
0  Supermarket Type1          3735.1380
2  Supermarket Type1          2097.2700
4  Supermarket Type1           994.7052
6  Supermarket Type1           343.5528
8  Supermarket Type1          1076.5986

SupType_2 DataFrame:
    Item_Weight Item_Fat_Content  Item_Visibility           Item_Type  \
1         5.920          Regular         0.019278         Soft Drinks
5        10.395          Regular         0.000000        Baking Goods
16       11.800          Low Fat         0.008596  Health and Hygiene
31       18.600          Low Fat         0.080829  Health and Hygiene
32       18.700          Low Fat         0.000000         Snack Foods

    Item_MRP  Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
1    48.2692                       2009      Medium               Tier 3
5    51.4008                       2009      Medium               Tier 3
16  115.3492                       2009      Medium               Tier 3
31   96.4436                       2009      Medium               Tier 3
32  256.6672                       2009      Medium               Tier 3

          Outlet_Type  Item_Outlet_Sales
1   Supermarket Type2           443.4228
5   Supermarket Type2           556.6088
16  Supermarket Type2          1621.8888
31  Supermarket Type2          2741.7644
32  Supermarket Type2          3068.0064